name: CD


concurrency:
  group: ${{ github.workflow }}-${{ inputs.stage }}-${{ github.ref }}
  cancel-in-progress: true


on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      connectors: ${{ steps.ls_connectors.outputs.list }}
    steps:
      - uses: actions/checkout@v4
      - id: ls_connectors
        run: |
          CONNECTORS=$(ls -d connectors/* | jq -R -s -c 'split("\n")[:-1]')
          echo "list=$CONNECTORS" >> $GITHUB_OUTPUT

  build-and-push:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        connector: ${{ fromJson(needs.discover.outputs.connectors) }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract connector name
        id: connector
        run: echo "name=$(basename ${{ matrix.connector }})" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          file: ./Dockerfile
          build-args: |
            CONNECTOR_PATH=${{ matrix.connector }}
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ steps.connector.outputs.name }}:latest
            ${{ vars.DOCKER_USERNAME }}/${{ steps.connector.outputs.name }}:${{ github.run_number }}
